/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ErrorCode = string;
export type ServiceName = string;

export interface Azure {
  configValidationMode?: "error" | "warn" | "off";
  console?:
    | boolean
    | {
        monitoring?: {
          logs?: {
            disabled?: boolean;
          };
          request?: {
            disabled?: boolean;
          };
          response?: {
            disabled?: boolean;
          };
        };
        org?: string;
      };
  custom?: {
    [k: string]: unknown;
  };
  dashboard?: {
    disableMonitoring?: boolean;
  };
  deprecationNotificationMode?: "error" | "warn" | "warn:summary";
  disabledDeprecations?: "*" | ErrorCode[];
  frameworkVersion?: string;
  functions?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9-_]+$".
     */
    [k: string]: {
      name?: string;
      events?: unknown[];
      [k: string]: unknown;
    };
  };
  package?: {
    artifact?: string;
    exclude?: string[];
    excludeDevDependencies?: boolean;
    include?: string[];
    individually?: boolean;
    path?: string;
    patterns?: string[];
  };
  params?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9-]+$".
     */
    [k: string]: {
      [k: string]: unknown;
    };
  };
  plugins?:
    | {
        localPath?: string;
        modules: string[];
      }
    | string[];
  projectDir?: string;
  provider: {
    [k: string]: unknown;
  };
  service: ServiceName;
  useDotenv?: true;
  variablesResolutionMode?: "20210219" | "20210326";
}
